# This is a basic workflow to help you get started with Actions

name: My first workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "unit-testing"
  unit-testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access i
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run Jest
        run: npm install && npm start
        
  
  # This workflow contains a single job called "sast", you should add these lines under "jobs", after "unit-testing"
  sast:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Synopsys Detect
        uses: synopsys-sig/detect-action@v0.3.0
        with:
          scan-mode: RAPID # Can be omitted, since this is the default value
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.9.0
          blackduck-url: "https://ingka.app.blackduck.com/"
          blackduck-api-token: ${{ secrets.BD_TOKEN }}

